language: go
sudo: false
go:
  - 1.5.4
  - 1.6.3
  - 1.7.3
  - tip

install:
  - go get -v github.com/qedus/osmpbf

script:
  - make race
  - make cover
  - make bench

after_success:
  - go get -v github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin
  - goveralls -coverprofile=profile.cov -service=travis-ci
